-- Données par défaut d'une nouvelle école (à exécuter dans la base Dolibarr, tables llx_, entité 1).
-- Équivalent de ce qu'installe l'activation des modules Classes, Élèves, Notes et Personnel.
-- INSERT IGNORE : sans effet sur ce qui existe déjà (même référence).
-- À exécuter après l'activation des modules (les tables et les niveaux doivent exister).

-- Classes : séries, créneaux, matières, classes
INSERT IGNORE INTO llx_ecole_section (entity, ref, label_fr, label_ar, position, date_creation, status) VALUES (1, 'C', 'Série C (mathématiques)', 'شعبة الرياضيات', 10, NOW(), 1);
INSERT IGNORE INTO llx_ecole_section (entity, ref, label_fr, label_ar, position, date_creation, status) VALUES (1, 'D', 'Série D (sciences naturelles)', 'شعبة العلوم الطبيعية', 20, NOW(), 1);
INSERT IGNORE INTO llx_ecole_section (entity, ref, label_fr, label_ar, position, date_creation, status) VALUES (1, 'A', 'Série A (lettres)', 'شعبة الآداب', 30, NOW(), 1);
INSERT IGNORE INTO llx_ecole_creneau (entity, ref, label_fr, label_ar, heure_debut, heure_fin, position, date_creation, status) VALUES (1, 'S1', 'Séance 1', 'الحصة 1', '08:00', '10:00', 10, NOW(), 1);
INSERT IGNORE INTO llx_ecole_creneau (entity, ref, label_fr, label_ar, heure_debut, heure_fin, position, date_creation, status) VALUES (1, 'S2', 'Séance 2', 'الحصة 2', '10:15', '12:15', 20, NOW(), 1);
INSERT IGNORE INTO llx_ecole_creneau (entity, ref, label_fr, label_ar, heure_debut, heure_fin, position, date_creation, status) VALUES (1, 'S3', 'Séance 3', 'الحصة 3', '15:00', '17:00', 30, NOW(), 1);
INSERT IGNORE INTO llx_ecole_creneau (entity, ref, label_fr, label_ar, heure_debut, heure_fin, position, date_creation, status) VALUES (1, 'S4', 'Séance 4', 'الحصة 4', '17:00', '19:00', 40, NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'MATH', 'MATH', 'Mathématiques', 'الرياضيات', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'PC', 'PC', 'Physique-Chimie', 'الفيزياء والكيمياء', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'SN', 'SN', 'Sciences naturelles', 'العلوم الطبيعية', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'FR', 'FR', 'Français', 'اللغة الفرنسية', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'AR', 'AR', 'Arabe', 'اللغة العربية', 'ar', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'ANG', 'ANG', 'Anglais', 'اللغة الإنجليزية', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'IR', 'IR', 'Instruction religieuse', 'التربية الإسلامية', 'ar', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'IC', 'IC', 'Instruction civique', 'التربية المدنية', 'ar', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'HG', 'HG', 'Histoire-Géographie', 'التاريخ والجغرافيا', 'ar', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'PHILO', 'PHILO', 'Philosophie', 'الفلسفة', 'ar', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'PENS', 'PENS', 'Pensée islamique', 'الفكر الإسلامي', 'ar', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'CORAN', 'CORAN', 'Coran', 'القرآن الكريم', 'ar', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'INFO', 'INFO', 'Informatique', 'المعلوماتية', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'EPS', 'EPS', 'Éducation physique et sportive', 'التربية البدنية والرياضية', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'DESSIN', 'DESSIN', 'Dessin', 'الرسم', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'EVEIL', 'EVEIL', 'Éveil scientifique', 'التربية العلمية', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'LECT', 'LECT', 'Lecture', 'القراءة', 'ar', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'ECRIT', 'ECRIT', 'Écriture', 'الكتابة', 'ar', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'DICT', 'DICT', 'Dictée', 'الإملاء', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'EXPR', 'EXPR', 'Expression écrite', 'التعبير الكتابي', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_matiere (entity, ref, code, label_fr, label_ar, langue, date_creation, status) VALUES (1, 'ACT', 'ACT', 'Activités pratiques', 'الأنشطة التطبيقية', 'fr', NOW(), 1);
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, 'PS', 'Petite section', 'القسم الصغير', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'MAT'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'MAT') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, 'MS', 'Moyenne section', 'القسم المتوسط', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'MAT'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'MAT') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, 'GS', 'Grande section', 'القسم الكبير', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'MAT'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'MAT') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '1AF', '1ère année fondamentale', 'السنة الأولى أساسية', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '2AF', '2ème année fondamentale', 'السنة الثانية أساسية', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '3AF', '3ème année fondamentale', 'السنة الثالثة أساسية', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '4AF', '4ème année fondamentale', 'السنة الرابعة أساسية', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '5AF', '5ème année fondamentale', 'السنة الخامسة أساسية', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '6AF', '6ème année fondamentale', 'السنة السادسة أساسية', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'PRI') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '1AS', '1ère année secondaire', 'السنة الأولى إعدادية', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'COL'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'COL') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '2AS', '2ème année secondaire', 'السنة الثانية إعدادية', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'COL'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'COL') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '3AS', '3ème année secondaire', 'السنة الثالثة إعدادية', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'COL'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'COL') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '4AS', '4ème année secondaire', 'السنة الرابعة إعدادية', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'COL'), NULL, 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'COL') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '5C', '5ème année C', 'السنة الخامسة ثانوية (ر)', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC'), (SELECT s.rowid FROM llx_ecole_section s WHERE s.entity = 1 AND s.ref = 'C'), 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '5D', '5ème année D', 'السنة الخامسة ثانوية (ع)', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC'), (SELECT s.rowid FROM llx_ecole_section s WHERE s.entity = 1 AND s.ref = 'D'), 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '5A', '5ème année A', 'السنة الخامسة ثانوية (آ)', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC'), (SELECT s.rowid FROM llx_ecole_section s WHERE s.entity = 1 AND s.ref = 'A'), 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '6C', '6ème année C', 'السنة السادسة ثانوية (ر)', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC'), (SELECT s.rowid FROM llx_ecole_section s WHERE s.entity = 1 AND s.ref = 'C'), 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '6D', '6ème année D', 'السنة السادسة ثانوية (ع)', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC'), (SELECT s.rowid FROM llx_ecole_section s WHERE s.entity = 1 AND s.ref = 'D'), 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '6A', '6ème année A', 'السنة السادسة ثانوية (آ)', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC'), (SELECT s.rowid FROM llx_ecole_section s WHERE s.entity = 1 AND s.ref = 'A'), 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '7C', '7ème année C', 'السنة السابعة ثانوية (ر)', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC'), (SELECT s.rowid FROM llx_ecole_section s WHERE s.entity = 1 AND s.ref = 'C'), 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '7D', '7ème année D', 'السنة السابعة ثانوية (ع)', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC'), (SELECT s.rowid FROM llx_ecole_section s WHERE s.entity = 1 AND s.ref = 'D'), 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC') IS NOT NULL;
INSERT IGNORE INTO llx_ecole_classe (entity, ref, label_fr, label_ar, fk_niveau, fk_section, effectif_max, mensualite, frais_inscription, date_creation, status) SELECT 1, '7A', '7ème année A', 'السنة السابعة ثانوية (آ)', (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC'), (SELECT s.rowid FROM llx_ecole_section s WHERE s.entity = 1 AND s.ref = 'A'), 100, 0, 0, NOW(), 1 FROM DUAL WHERE (SELECT n.rowid FROM llx_ecole_niveau n WHERE n.entity = 1 AND n.ref = 'LYC') IS NOT NULL;

-- Élèves : autres frais, modes de paiement
INSERT IGNORE INTO llx_ecole_frais_type (entity, ref, label_fr, label_ar, montant, position, date_creation, status) VALUES (1, 'UNIFORME', 'Uniforme', 'الزي المدرسي', 0, 10, NOW(), 1);
INSERT IGNORE INTO llx_ecole_frais_type (entity, ref, label_fr, label_ar, montant, position, date_creation, status) VALUES (1, 'FOURNITURES', 'Fournitures scolaires', 'الأدوات المدرسية', 0, 20, NOW(), 1);
INSERT IGNORE INTO llx_ecole_frais_type (entity, ref, label_fr, label_ar, montant, position, date_creation, status) VALUES (1, 'TRANSPORT', 'Transport', 'النقل', 0, 30, NOW(), 1);
INSERT IGNORE INTO llx_ecole_frais_type (entity, ref, label_fr, label_ar, montant, position, date_creation, status) VALUES (1, 'CANTINE', 'Cantine', 'المطعم المدرسي', 0, 40, NOW(), 1);
INSERT IGNORE INTO llx_c_paiement (entity, code, libelle, type, active, position) VALUES (1, 'BANKIL', 'Bankily', 2, 1, 0);
INSERT IGNORE INTO llx_c_paiement (entity, code, libelle, type, active, position) VALUES (1, 'MASRVI', 'Masrvi', 2, 1, 0);
INSERT IGNORE INTO llx_c_paiement (entity, code, libelle, type, active, position) VALUES (1, 'SEDAD', 'Sedad', 2, 1, 0);

-- Notes : mention P.Tr
INSERT IGNORE INTO llx_ecole_note_mention (entity, ref, label_fr, label_ar, seuil, date_creation, status) VALUES (1, 'PTR', 'P.Tr', NULL, 8, NOW(), 1);

-- Personnel : jours fériés fixes (année scolaire 2026-2027)
INSERT IGNORE INTO llx_ecole_jour_sans_cours (entity, ref, label_fr, label_ar, date_debut, date_fin, description, date_creation, status) VALUES (1, 'NOUVEL_AN-2027', 'Nouvel an', 'رأس السنة الميلادية', '2027-01-01', '2027-01-01', 'Jour férié', NOW(), 1);
INSERT IGNORE INTO llx_ecole_jour_sans_cours (entity, ref, label_fr, label_ar, date_debut, date_fin, description, date_creation, status) VALUES (1, 'TRAVAIL-2027', 'Fête du travail', 'عيد العمال', '2027-05-01', '2027-05-01', 'Jour férié', NOW(), 1);
INSERT IGNORE INTO llx_ecole_jour_sans_cours (entity, ref, label_fr, label_ar, date_debut, date_fin, description, date_creation, status) VALUES (1, 'AFRIQUE-2027', 'Journée de l\'Afrique', 'يوم إفريقيا', '2027-05-25', '2027-05-25', 'Jour férié', NOW(), 1);
INSERT IGNORE INTO llx_ecole_jour_sans_cours (entity, ref, label_fr, label_ar, date_debut, date_fin, description, date_creation, status) VALUES (1, 'FORCES-2027', 'Fête des forces armées', 'عيد القوات المسلحة', '2027-07-10', '2027-07-10', 'Jour férié', NOW(), 1);
INSERT IGNORE INTO llx_ecole_jour_sans_cours (entity, ref, label_fr, label_ar, date_debut, date_fin, description, date_creation, status) VALUES (1, 'INDEPENDANCE-2026', 'Fête de l\'indépendance', 'عيد الاستقلال', '2026-11-28', '2026-11-28', 'Jour férié', NOW(), 1);

-- Réglages par défaut (seulement s'ils ne sont pas déjà réglés)
INSERT IGNORE INTO llx_const (name, entity, value, type, visible, note) VALUES ('ELEVES_MOIS_PAYANTS', 1, '10,11,12,1,2,3,4,5,6', 'chaine', 0, '');
INSERT IGNORE INTO llx_const (name, entity, value, type, visible, note) VALUES ('ELEVES_JOUR_LIMITE', 1, '10', 'chaine', 0, '');
INSERT IGNORE INTO llx_const (name, entity, value, type, visible, note) VALUES ('ELEVES_RECU_FORMAT', 1, 'A5', 'chaine', 0, '');
INSERT IGNORE INTO llx_const (name, entity, value, type, visible, note) VALUES ('ELEVES_WHATSAPP_INDICATIF', 1, '222', 'chaine', 0, '');
INSERT IGNORE INTO llx_const (name, entity, value, type, visible, note) VALUES ('ELEVES_SEUIL_ABSENCES', 1, '10', 'chaine', 0, '');
INSERT IGNORE INTO llx_const (name, entity, value, type, visible, note) VALUES ('ELEVES_SEUIL_RETARDS', 1, '5', 'chaine', 0, '');
INSERT IGNORE INTO llx_const (name, entity, value, type, visible, note) VALUES ('ECOLE_JOURS_OUVRABLES', 1, '1,2,3,4,5,6', 'chaine', 0, '');
